version: '2'

services:
  alfresco-core:
    image: ${DOCKER_IMAGE}
    ports:
    - ${DOCKER_IP}::8080
    - "8000:8000"
    volumes:
    - alfresco:/opt/alfresco/alf_data
    restart: unless-stopped
    environment:
    - DEBUG=true
    - DB_NAME=alfresco
    - DB_USERNAME=alfresco
    - DB_PASSWORD=admin
    - DB_URL=jdbc:postgresql://postgresql:5432/alfresco
    - DB_DRIVER=org.postgresql.Driver
    - SOLR_HOST=solr
    - SOLR_PORT=8081
    - SOLR_PORT_SSL=8444
    - JAVA_XMS=511M
    - JAVA_XMX=2048M
    - GLOBAL_content.transformer.RemoteJODConverter.endpoint=http://jodconverter:8080/converter/service
    - GLOBAL_ooo.enabled=false
    - GLOBAL_jodconverter.enabled=false

  solr:
    image: hub.xenit.eu/alfresco-solr4:build-201809071427-19
    restart: unless-stopped
    environment:
    - ALFRESCO_HOST=alfresco-core
    - ALFRESCO_PORT=8080
    - ALFRESCO_PORT_SSL=8443
    - SOLR_PORT=8081
    - SOLR_PORT_SSL=8444
    - JAVA_XMS=512M
    - JAVA_XMX=2048M

  postgresql:
    image: hub.xenit.eu/postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
    - "PGCONF_log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '"
    - PGCONF_log_checkpoints=on
    - PGCONF_log_connections=on
    - PGCONF_log_disconnections=on
    - PGCONF_log_lock_waits=on
    - PGCONF_log_temp_files=0
    - PGCONF_log_autovacuum_min_duration=0
    - PGCONF_log_error_verbosity=default
    - PGCONF_log_min_duration_statement=100
    #    - PGCONF_log_duration=on
    restart: unless-stopped

  jodconverter:
    image: hub.xenit.eu/jodconverter-ws
    restart: unless-stopped


volumes:
  alfresco:
  solr:
  postgres: